### ISSUE TITLE
LGVI checkpoint missing keys

### ISSUE THREAD

**Issue by hyunbin70** [jianzongwu/Language-Driven-Video-Inpainting#5]
Hi, Thank you for your excellent work.

I tried to inference LGVI for referring expressions using the repo on https://huggingface.co/jianzongwu/lgvi.
I cloned this repo in ./checkpoints and run the following command as described in README:

python -m inference_referring \
  --video_path videos/two-birds \
  --ckpt_path checkpoints/lgvi \
  --expr "remove the bird on left" \
  
  But I encountered Error like this:
  The config attributes {'st_attn': False} were passed to RoviModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hboh/neurips24/Language_Driven_Video_Inpainting/inference_referring.py", line 86, in <module>
    main(args)
  File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/hboh/neurips24/Language_Driven_Video_Inpainting/inference_referring.py", line 45, in main
    unet = RoviModel.from_pretrained(args.ckpt_path, subfolder='unet')
  File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 660, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'rovi.models.unet.RoviModel'> from /home/hboh/neurips24/Language_Driven_Video_Inpainting/checkpoints/lgvi because the following keys are missing:
 condition_conv_in.bias, condition_conv_in.weight.
 Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
 
 I think it's because lgvi checkpoint is something wrong.
 When I do the same inference for referring expressions with **lgvi-i checkpoint** on repo https://huggingface.co/jianzongwu/lgvi-i, it works fine with the provided videos (two-birds and city-bird).
 
Thank you for replying in advance! :)
 
p.s. Additionally, I would appreciate your insights on how well the model generalizes to other in-the-wild videos. Your honest feedback would be very helpful.

**Comment by DebbyX3** [comment]
I have the same issue! 

I also have problems with LGVI-I, but the error is not the same:

Following the README, I run:
```
python -m inference_interactive \
  --video_path videos/city-bird \
  --ckpt_path checkpoints/lgvi-i \
  --request "I have this incredible shot of a pelican gliding in the sky, but there's another bird also captured in the frame. Can you help me make the picture solely about the pelican?" \
```

Error: 
```
Traceback (most recent call last):
  File "/home/labvips-ub/anaconda3/envs/rovi/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/labvips-ub/anaconda3/envs/rovi/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/inference_interactive.py", line 14, in <module>
    from rovi.pipelines.pipeline_rovi_mllm import RoviPipelineMLLM
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/pipelines/pipeline_rovi_mllm.py", line 31, in <module>
    from rovi.llm.llava.conversation import conv_templates, SeparatorStyle
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/model/language_model/llava_llama.py", line 27, in <module>
    from ..llava_arch import LlavaMetaModel, LlavaMetaForCausalLM
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/model/llava_arch.py", line 24, in <module>
    from llava.constants import IGNORE_INDEX, IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_PATCH_TOKEN, DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/model/__init__.py", line 1, in <module>
    from .language_model.llava_llama import LlavaLlamaForCausalLM, LlavaConfig
  File "/home/labvips-ub/3D Gaussian Splatting/Language-Driven-Video-Inpainting/rovi/llm/llava/model/language_model/llava_llama.py", line 139, in <module>
    AutoConfig.register("llava", LlavaConfig)
  File "/home/labvips-ub/anaconda3/envs/rovi/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 981, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/home/labvips-ub/anaconda3/envs/rovi/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 680, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.
```

**Comment by hyunbin70** [comment]
Hi, DebbyX3.
Actually, I encountered same value error you’ve mentioned:
ValueError: 'llava' is already used by a Transformers config, pick another name.

I could solve this error by downgrading ‘transformers’ package in pip.

**Comment by DebbyX3** [comment]
> Hi, DebbyX3. Actually, I encountered same value error you’ve mentioned: ValueError: 'llava' is already used by a Transformers config, pick another name.
> 
> I could solve this error by downgrading ‘transformers’ package in pip.

Hi, yes I actually already tried to downgrade 'transformers', but it didn't solve the problem (the error was just different), I probably picked the wrong version. 
Can you share which version you were successful with?

**Comment by longyangqi** [comment]
@hyunbin70 the same problem!
Have you fix the issue?

**Comment by jianzongwu** [comment]
> Hi, Thank you for your excellent work.
> 
> I tried to inference LGVI for referring expressions using the repo on https://huggingface.co/jianzongwu/lgvi. I cloned this repo in ./checkpoints and run the following command as described in README:
> 
> python -m inference_referring --video_path videos/two-birds --ckpt_path checkpoints/lgvi --expr "remove the bird on left" \
> 
> But I encountered Error like this: The config attributes {'st_attn': False} were passed to RoviModel, but are not expected and will be ignored. Please verify your config.json configuration file. Traceback (most recent call last): File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/home/hboh/neurips24/Language_Driven_Video_Inpainting/inference_referring.py", line 86, in main(args) File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/hboh/neurips24/Language_Driven_Video_Inpainting/inference_referring.py", line 45, in main unet = RoviModel.from_pretrained(args.ckpt_path, subfolder='unet') File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn return fn(*args, **kwargs) File "/home/hboh/anaconda3/envs/rovi/lib/python3.9/site-packages/diffusers/models/modeling_utils.py", line 660, in from_pretrained raise ValueError( ValueError: Cannot load <class 'rovi.models.unet.RoviModel'> from /home/hboh/neurips24/Language_Driven_Video_Inpainting/checkpoints/lgvi because the following keys are missing: condition_conv_in.bias, condition_conv_in.weight. Please make sure to pass `low_cpu_mem_usage=False` and `device_map=None` if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
> 
> I think it's because lgvi checkpoint is something wrong. When I do the same inference for referring expressions with **lgvi-i checkpoint** on repo https://huggingface.co/jianzongwu/lgvi-i, it works fine with the provided videos (two-birds and city-bird).
> 
> Thank you for replying in advance! :)
> 
> p.s. Additionally, I would appreciate your insights on how well the model generalizes to other in-the-wild videos. Your honest feedback would be very helpful.

Hello, sorry for the late reply.
The problem may be caused by a bug in the LGVI unet config file. I have fixed the config in https://huggingface.co/jianzongwu/lgvi/unet/config.json. You can download the new config file or simply copy the following content into your local config file.
Please let me know if you have any other issues!

```
{
  "_class_name": "RoviModel",
  "_diffusers_version": "0.21.4",
  "act_fn": "silu",
  "attention_head_dim": 8,
  "block_out_channels": [
    320,
    640,
    1280,
    1280
  ],
  "center_input_sample": false,
  "class_embed_type": null,
  "cross_attention_dim": 768,
  "cross_frame_type": null,
  "down_block_types": [
    "CrossAttnDownBlock3D",
    "CrossAttnDownBlock3D",
    "CrossAttnDownBlock3D",
    "DownBlock3D"
  ],
  "downsample_padding": 1,
  "dual_cross_attention": false,
  "flip_sin_to_cos": true,
  "freq_shift": 0,
  "in_channels": 8,
  "lan_cross_attn": false,
  "layers_per_block": 2,
  "mask_decoder_type": "MaskDecoder",
  "mid_block_scale_factor": 1,
  "mid_block_type": "UNetMidBlock3DCrossAttn",
  "norm_eps": 1e-05,
  "norm_num_groups": 32,
  "num_class_embeds": null,
  "only_cross_attention": false,
  "out_channels": 4,
  "ref_frame_type_2": null,
  "resnet_time_scale_shift": "default",
  "sample_size": 64,
  "temp_attn": true,
  "up_block_types": [
    "UpBlock3D",
    "CrossAttnUpBlock3D",
    "CrossAttnUpBlock3D",
    "CrossAttnUpBlock3D"
  ],
  "upcast_attention": false,
  "use_linear_projection": false
}
```
